<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Attributes\Fillable;

#[Fillable([
    'epoxy_product_id',
    'color_id',
    'epoxy_filler_color_id',
    'formula_snapshot',
    'quantity',
    'operator_id',
    'remarks',
])]
class EpoxyAssembly extends Model
{
    protected function casts(): array
    {
        return [
            'formula_snapshot' => 'array',
            'quantity' => 'integer',
        ];
    }

    /**
     * Get the product.
     */
    public function product(): BelongsTo
    {
        return $this->belongsTo(EpoxyProduct::class, 'epoxy_product_id');
    }

    /**
     * Get the color (from Grout Colors).
     */
    public function color(): BelongsTo
    {
        return $this->belongsTo(Color::class, 'color_id');
    }

    /**
     * Get the epoxy filler color.
     */
    public function epoxyFillerColor(): BelongsTo
    {
        return $this->belongsTo(EpoxyFillerColor::class, 'epoxy_filler_color_id');
    }

    /**
     * Get the operator who assembled this.
     */
    public function operator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'operator_id');
    }

    /**
     * Get the stock ledger records generated by this assembly.
     */
    public function ledgers(): HasMany
    {
        return $this->hasMany(StockLedger::class, 'epoxy_assembly_id');
    }

    /**
     * Get the brand of the product associated with this assembly.
     */
    public function getBrandAttribute(): ?Brand
    {
        return $this->product?->brand;
    }

    /**
     * Scope a query to include epoxy assemblies for a specific brand or common products via EpoxyProduct relation.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  \App\Models\Brand|int|string|null  $brand
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeForBrand($query, $brand = null)
    {
        $brandId = $brand instanceof Brand ? $brand->id : $brand;
        if (!$brandId) {
            return $query;
        }
        return $query->whereHas('product', function ($q) use ($brandId) {
            $q->forBrand($brandId);
        });
    }

    /**
     * Scope a query to include epoxy assemblies for the current session brand or common products.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeForCurrentBrand($query)
    {
        $currentBrand = function_exists('currentBrand') ? currentBrand() : null;
        return $this->scopeForBrand($query, $currentBrand?->id);
    }
}
